# Generated by Django 5.2.1 on 2025-05-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='projet.reservation'),
        ),
    ]
